sql:
    surreal sql -u root -p jour

start-surreal:
    surreal start --auth -u root -p jour

start-surreal-file:
    surreal start --auth -u root -p jour file:surreal/dev.db

import:
    surreal import --conn http://localhost:8000 -u root -p jour --namespace jour --database dev init.surql

export:
    surreal export --conn http://localhost:8000 -u root -p jour --namespace jour --database dev init.surql
