list:
    surrealdb-migrations list --password jour --ns jour --db dev

apply:
    surrealdb-migrations apply --password jour --ns jour --db dev

apply-dry-run:
    surrealdb-migrations apply --password jour --ns jour --db dev --dry-run

